### ISSUE TITLE
error: unknown type name 'http_context_t'

### ISSUE THREAD

**Issue by mau-lopez** [igrr/esp32-cam-demo#104]
Hi, just cloned esp32-cam-demo, and while making I get the attached compiler errors, all related with http_context_t, has anybody had the same or similar error? or any idea of how to solve it? Thanks in advance

Macbook Pro Mid 2015, MacOS 10.14
esp-idf cloned on Oct 26, 2018

<img width="710" alt="screen shot 2018-10-29 at 18 21 28" src="https://user-images.githubusercontent.com/44591974/47688030-e81cf280-dba8-11e8-81d9-8f839c388fcf.png">

**Comment by fah** [comment]
Same here. Replaced the include of "http_server.h" by "esp_http_server.h" then got the messages above. Found no solution.

**Comment by fah** [comment]
Solution: (tested on MacOSX)
1. go into components folder
1. remove http-server folder
1. execute ````git clone https://github.com/igrr/esp32-http-server.git````
1. go back to root of project and execute ````make flash monitor`````

**Comment by mau-lopez** [comment]
Thanks a lot for your help fah, indeed it worked, no more compiling errors. Closing this issue now.

**Comment by WJohnnyW** [comment]
it really works! Thank you from the bottom of my heart!

**Comment by treii28** [comment]
thanks, ran into this today
