### ISSUE TITLE
Refactor the code to use i2s_dev_t structure instead of register macros.

### ISSUE THREAD

**Issue by igrr** [igrr/esp32-cam-demo#14]
Currently large chunks of code look like a scary uppercase mess. Would be great to rewrite the code to use structure definitions found in `soc/i2s_struct.h` for better readability.

**Comment by krzychb** [comment]
@igrr, [soc/i2s_struct.h](https://github.com/espressif/esp-idf/blob/master/components/esp32/include/soc/i2s_struct.h) looks like a blank slate not having any inline comments. Do you have an estimate date to get it documented?

**Comment by igrr** [comment]
Frankly I never thought about documenting struct header files. For the I2S it's a bit unclear where the documentation would come from, as there is no I2S chapter in the TRM (yet).
