### ISSUE TITLE
Missing esp_intr_alloc.h

### ISSUE THREAD

**Issue by krzychb** [igrr/esp32-cam-demo#16]
With commit https://github.com/igrr/esp32-cam-demo/commit/cf5d8a1637544ad2b9209c4faebd5c3735b9af3b I am getting the following error:

C:/msys32/esp/esp32-cam-demo/components/camera/camera.c:44:28: fatal error: esp_intr_alloc.h: No such file or directory
 #include "esp_intr_alloc.h"
                            ^
compilation terminated.

**Comment by donny681** [comment]
I meet the same problem,Maybe he forget to post the code..

**Comment by donny681** [comment]
I facethe same problem,Maybe he forget to post the code..

**Comment by donny681** [comment]
I face the same problem,Maybe he forget to post the code.

**Comment by krzychb** [comment]
I hope this file is stacked with broken master branch https://twitter.com/i_grr/status/807192758783836160

**Comment by igrr** [comment]
Sorry about that. No, the master branch of ESP-IDF was broken, hence some commits (including the new interrupt allocation feature) haven't been deployed to Github.

**Comment by krzychb** [comment]
For latest esp-idf (with commits as of 13-Dec-2015) this error is not reported anymore.
