### ISSUE TITLE
Using default sdkconfig is causing application to get stuck on random basis waiting for a frame

### ISSUE THREAD

**Issue by krzychb** [igrr/esp32-cam-demo#19]
Application gets stuck on the following step:
```
D (2825) camera: Waiting for frame
```

This happens on random basis, after reset and (always) successfully displaying the first frame.
Then, in two out of three cases, application gets stuck on the second frame.
If second frame is displayed successfully, then application continue to operate normally.

To replicate this issue use settings as on the left below. 
Settings on the right do not cause any issues and are as used so far in this repository.

![image](https://cloud.githubusercontent.com/assets/12953787/21268609/cd7cbea0-c3af-11e6-9036-901a869ed40e.png)

To change settings go to `Component config > ESP32-specific config > Task watchdog`
 
I have discovered this issue when checking generation of default `sdkconfig` file with `make defconfig`.
By default "Wathdog task" is enabled.

**Comment by krzychb** [comment]
For the record attached is `sdkconfig` that is not causing this issue. 
Remove .txt extension if you like to use it in your project.
[sdkconfig.txt](https://github.com/igrr/esp32-cam-demo/files/678673/sdkconfig.txt)

Now, if you delete it, as well as `sdkconfig.old` and run `make defconfig` to get default configuration (or `make menuconfig`), the application gets stuck as described above.

I see new development with current `esp-idf`. If you disable the Watchdog task, it will not resolve the issue. This indicates that some other settings in `sdkconfig` may be the troublemaker. So far I was unable to pin point the settings. Fortunately there are no many differences.

**Comment by krzychb** [comment]
To complete this troubleshooting session, below is summary of differences between DEFAULT and GOOD configuration files. 

1. CONFIG_TASK_WDT
![capture1](https://cloud.githubusercontent.com/assets/12953787/21566318/4283e014-cea2-11e6-8206-3c02f89a5917.PNG)

2. CONFIG_FREERTOS_UNICORE
3. CONFIG_FREERTOS_CHECK_STACKOVERFLOW_NONE
![capture2](https://cloud.githubusercontent.com/assets/12953787/21566322/48623b84-cea2-11e6-9f9d-4232a8fd778c.PNG)

4. CONFIG_LOG_DEFAULT_LEVEL_INFO
![capture3](https://cloud.githubusercontent.com/assets/12953787/21566324/4a10bbd6-cea2-11e6-8892-f1b3cc2108b0.PNG)

Removing each individual difference in DEFAULT configuration does not resolve the issue.

**Comment by igrr** [comment]
Fixed in #31
