### ISSUE TITLE
Send out through wifi after a row of data has been collected.Every sendto API has been called,but almost half of udp packet is missing.

### ISSUE THREAD

**Issue by jixunx** [igrr/esp32-cam-demo#25]
The demand of my project is to collect the data of camera by ESP32, and then send it to PC in real time by wifi. LAN transmission.It is similar to demand for real-time monitoring.
My design is(modify line_filter_task to udp_thread) :ESP32 collects camera data through I2S protocol.I set the I2S DMA ping-pang buffer.When a buffer is full, I2S interrupt will occuer.In the ISR, let the camera data fill into another buffer, and then notify the UDP thread to send the data from the DMA buffer which has just been filled to PC through wifi.
Here is my i2s_isr code:
CODE: SELECT ALL
static void IRAM_ATTR i2s_isr(void* arg)
{
   I2S0.conf.rx_start = 0;
   I2S0.int_clr.val = I2S0.int_raw.val;       
   /******************switch buffer to let camera data fill***************************/              
       s_cur_buffer = !s_cur_buffer;
     if (s_isr_count == 239) 
   {
      i2s_stop();
       }
   else 
       {
          ++s_isr_count;
   }
   i2s_fill_buf(s_cur_buffer);
   BaseType_t xHigherPriorityTaskWoken;
   /******************notify udp_thread***************************/     
       xSemaphoreGiveFromISR(s_data_ready, &xHigherPriorityTaskWoken);
       if (xHigherPriorityTaskWoken != pdFALSE) 
   {      
           portYIELD_FROM_ISR();
       }
}

Here is my UDP_thread code:
CODE: SELECT ALL
void udp_thread(void *p)
{
      int prev_buf = -1;
      int sock;
      struct sockaddr_in toAddr;
      LWIP_UNUSED_ARG(p);
      sock = socket(AF_INET,SOCK_DGRAM,IPPROTO_UDP);
      if(sock < 0)
      {
         ESP_LOGI(TAG, "socket err");
      }
      memset(&toAddr,0,sizeof(toAddr));
      toAddr.sin_family=AF_INET;
      toAddr.sin_addr.s_addr=inet_addr("192.168.23.1");
      toAddr.sin_port = htons(REMOTE_PORT);
      while (true) 
      {
                        /******************waiting notification from udp_i2s_isr***************************/     
         xSemaphoreTake(s_data_ready, portMAX_DELAY);
                        FD_ZERO(&rdfds); 
         FD_SET(sock,&rdfds); 
         usertimeout.tv_sec=0;
         usertimeout.tv_usec=1000;
                        /******************buf_idx is the buffer which has just been filled fully ***************************/   
         int buf_idx = !s_cur_buffer;
         if (prev_buf != -1 && prev_buf == buf_idx) 
         {     
            ets_printf("! %d\n", s_line_count);
         }
                        const uint32_t* buf = s_dma_buf[buf_idx];
         prev_buf = buf_idx;
                        /******************A frame has been collected fully from  camera***************************/  
         if (!s_i2s_running) 
         {
            prev_buf = -1;
            s_frame_count++;
                                /******************frame_end tells the receiver that this is the end of this frame***************************/   
            sendto(sock,frame_end,SEND_END_LEN ,0,(struct sockaddr*)&toAddr,sizeof(toAddr));
                                /******************new fram collect***************************/ 
            i2s_run(s_fb_w, s_fb_h);
                               /******************frame_start tells the receiver that this is the start of this frame***************************/   
            sendto(sock,frame_start,SEND_START_LEN ,0,(struct sockaddr*)&toAddr,sizeof(toAddr));
            continue;
         }
         ret=select(sock+1,NULL,&rdfds,NULL,&usertimeout);

         if(ret < 0) 
         {
            perror("select error\n");
         }
         else if(ret == 0)
         {
            printf("time out\n"); 
         }
         else
         { 
                 if(FD_ISSET(sock,&rdfds))   
            {
            /******************send the part of centent of frame.***************************/  
               sendto(sock,buf,960,0,(struct sockaddr*)&toAddr,sizeof(toAddr));
                                        ++s_line_count;
            }
              
                   }
         }
            close(sock);
            vTaskDelete(NULL);
}

My problem is:According to my debugging,every sendto API that should be called has been called.But From my observation on Wireshark,more than half of the UDP package is missing.The time that sento API needs to run is more than sufficient.
From my guess,wiFi task hasn't finished yet,but new data coming in.So these data cannot be sent out.I don't know the detail about wifi stack in ESP32.
Can you share your opinion about it.I will be appreciate it very much.

**Comment by igrr** [comment]
Hi, I think you may have [posted the same question](https://esp32.com/viewtopic.php?f=2&t=931) on the esp32.com forum. I will let you know my thoughts there. As it stands, i don't think that this project's issue tracker is a good place to offer you help developing your application, because it is only related to this project by the fact that it uses a camera and an ESP32 :)
