### ISSUE TITLE
More or less a pixel randomly occured when wifi is connecting.

### ISSUE THREAD

**Issue by jixunx** [igrr/esp32-cam-demo#27]
Wifi is connecting,according my  investigation,when esp32 collects data from camera ,more or less a pixel occured randomly.It lead to data of the line shift.So this line will be wrong.If this issue cann't be avoided,what measures should be taken on the software?
![5](https://cloud.githubusercontent.com/assets/25680280/24496771/bf9a9b5a-156b-11e7-8db3-494b76c917a4.jpg)

**Comment by krzychb** [comment]
It looks to me that the same issue is posted on [esp32.com forum](https://www.esp32.com/viewtopic.php?f=2&t=1565) . I think that forum is more appropriate place to discuss it since **esp32-cam-demo** does not have any Wi-Fi functionality implemented.
