### ISSUE TITLE
SCCB Pull-ups?

### ISSUE THREAD

**Issue by hopkinskong** [igrr/esp32-cam-demo#28]
Hi, do I need to use pull-up resistors on the SCCB lines?

**Comment by hopkinskong** [comment]
Answering my own question after two weeks without response:

No, it does not need external pull-up resistors as I can configure the GPIOs to use internal pull-ups.

**Comment by xloc** [comment]
Hello. But can I add external pull-up resistors to these two lines?
I have to use these two lines for I2C communication, and for it, external resistors are recommended.
