### ISSUE TITLE
analog video input

### ISSUE THREAD

**Issue by avtehnik** [igrr/esp32-cam-demo#34]
Hi. 
Is it possible  to connect analog video encoder like saa7113h/ADV7181 to esp32?  

saa7113h system clock out 27MHz, is esp32 can handle it ?
Thanks.

![image](https://user-images.githubusercontent.com/3436529/26936438-635fe8c0-4c77-11e7-87ae-ddf4af0831ea.png)

**Comment by igrr** [comment]
I2S can only reliably sample the input up to 20MHz. At 27 MHz you would be loosing samples every now and then. Possibly okay for grayscale images when image quality isn't a concern, but i don't think it is good enough for general purpose use case.
There are some improvements to I2S peripheral in the pipeline though, so maybe in the next chip we can support up to 40MHz input.
