### ISSUE TITLE
Read frame data

### ISSUE THREAD

**Issue by hechao** [igrr/esp32-cam-demo#38]
Hello!

Very cool project! Thanks for making this.

I have tried the demo, but the code seems updated, the question is how to read the data downloaded from http://192.168.0.104/get

I have tried to rename the file from http://192.168.0.104/pgm to pgm.pgm, and open it with a tool called openseeit, it is very grey rough image. This is a problem of the camera or what could be?
![pgmpgm](https://user-images.githubusercontent.com/1189984/27220538-11735a14-52b8-11e7-9cad-c48c785df39a.png)

**Comment by igrr** [comment]
If you are using OV7725 in grayscale mode, `http://your-ip/get` returns raw image (without any headers), one byte per pixel. `/pgm` should return the same, plus PGM header. I can't really tell whether this result you get is due to an issue with hardware, code, or the viewer.
Can you attach this PGM file you get, or post a link to it?

**Comment by hechao** [comment]
Yes, sure, thank you very much for the swift reply.

Using 7725 camera, hardware data pin is D2-D7 (D0 D1 should be not used right?), Reset pin set to IO15, the rest is fully same.
[pgm.zip](https://github.com/igrr/esp32-cam-demo/files/1080428/pgm.zip)

Also when I turn on "[ ] Enable test pattern on camera", and also OV7725 and OV2640, the test pattern not working. One more question, is OV2640 also supported now?

Thank you!!

**Comment by igrr** [comment]
The image looked posterized, so i checked the histogram. Here is the histogram of image bytes:
<img width="391" alt="screen shot 2017-06-16 at 18 33 14" src="https://user-images.githubusercontent.com/4349050/27223270-4c54d64e-52c2-11e7-9c62-51d0083c0b98.png">

See that periodic structure? There are ranges of values, each is 16 units wide. This doesn't look like a random error.

Here is a histogram of *bits* in your image. It makes me think that two wires/pins from the camera are not connected. If i'm not mistaken, that's D7 and D6:

<img width="402" alt="screen shot 2017-06-16 at 18 31 08" src="https://user-images.githubusercontent.com/4349050/27223229-2ca97fca-52c2-11e7-8ea0-95a284de2ef5.png">

**Comment by igrr** [comment]
OV2640 is supported now, although it is still has some random glitches in JPEG mode at 20MHz (might be signal integrity issue on WROVER-KIT board).

W.r.t. test pattern not working, can you give more info? Any error log? If there is no error, do you get some image instead?

**Comment by hechao** [comment]
Thanks, will check this and let you know later.

**Comment by hechao** [comment]
need some time to check it, will close it now, thanks for support
