### ISSUE TITLE
Only getting 4MHz period on the XCLK pin ...

### ISSUE THREAD

**Issue by nkolban** [igrr/esp32-cam-demo#42]
I decided to put a signal analyzer on the XCLCK and PCLK pins and what I find is that the frequency is 4MHZ (using the code in this project).

I think I had expected 20MHz based on the logic within.  Has anyone else measured the clock rate on the pins and have either the same or different results?

<img width="751" alt="2017-07-22_22-49-53" src="https://user-images.githubusercontent.com/3421732/28496412-24eaca98-6f30-11e7-9f40-49e041bbf864.png">

**Comment by igrr** [comment]
Hi Neil, I have connected the board to the logic analyzer and got the following:

<img width="1052" alt="screen shot 2017-11-08 at 11 22 42" src="https://user-images.githubusercontent.com/4349050/32530143-f865f70a-c401-11e7-8321-4ced7318190c.png">

That's with the code cloned from github, only change was to set WiFi SSID and password in menuconfig.
Perhaps you have 4MHz frequency accidentally set in sdkconfig?
