### ISSUE TITLE
OV2640 eeserved registers

### ISSUE THREAD

**Issue by JPMJPM** [igrr/esp32-cam-demo#49]
Hi,

In ov2640.c -->

static const uint8_t jpeg_regs[][2] = {
        { BANK_SEL, BANK_SEL_DSP },
        { RESET,   RESET_DVP},
        { IMAGE_MODE, IMAGE_MODE_JPEG_EN|IMAGE_MODE_RGB565 },
        { 0xD7,     0x03 },
        { 0xE1,     0x77 },
        { QS,       0x0C },
        { RESET,    0x00 },
        {0, 0},
};

But in OV2640 datasheet registers 0xD7 and 0xE1 appears as reserved.

Any help ?.

Regards.

**Comment by igrr** [comment]
That code comes from OpenMV, https://github.com/openmv/openmv/blob/master/src/omv/ov2640.c, so frankly i don't have a clue. Perhaps they have a more up to date datasheet?..
