### ISSUE TITLE
OV2640 probe failed with error 

### ISSUE THREAD

**Issue by LilyGO** [igrr/esp32-cam-demo#57]
E (273) camera_demo: Camera probe failed with error 0x20003

**Comment by LilyGO** [comment]
![screenshot_13](https://user-images.githubusercontent.com/31160602/33826984-b26eb7ea-dea1-11e7-89b4-cdbb9a8ab9d1.png)

**Comment by Oitzu** [comment]
0x20003 is Camera not supported.
Two causes can lead to this error:
1.) Camera-Model not activated in config.
2.) Not the correct answer over SCCB from the camera.

I guess number 1. ;)

**Comment by igrr** [comment]
Might be related to https://github.com/igrr/esp32-cam-demo/issues/37. See if toggling power to the camera helps.

**Comment by LilyGO** [comment]
![image](https://user-images.githubusercontent.com/31160602/33863359-4787ab18-df22-11e7-8a2a-c365b809903c.png)

**Comment by LilyGO** [comment]
When I recompile upload, the error was upgraded. My XCLK pin is 21. I do not understand why something goes wrong. I just started getting in touch with ESP32 last month, but I want to figure it out. This looks cool. thank you all.

**Comment by LilyGO** [comment]
@Oitzu hi,Oitzu.Camera model is not activated in configuration. Where to modify the configuration. Is it here, my module is ov2640

**Comment by LilyGO** [comment]
![screenshot_15](https://user-images.githubusercontent.com/31160602/33863728-2e6da464-df24-11e7-95f9-ebf7197d0180.png)

**Comment by igrr** [comment]
Given the log posted in https://github.com/igrr/esp32-cam-demo/issues/61, i think this issue is solved.

**Comment by LilyGO** [comment]
Yes, thank you for your help.Adherence is victory.

**Comment by 9lash** [comment]
**It looks like this issue is closed but doesnt seem to work for me. I get the following output:** 

![camera](https://user-images.githubusercontent.com/547048/50037943-3c572700-ffdd-11e8-9b32-b881f93451bd.PNG)

**Pin configuration is as follows:** 
![pin config](https://user-images.githubusercontent.com/547048/50037968-893afd80-ffdd-11e8-8866-d2eac7fa9654.PNG)

To flash the firmware, I connected GPIO0  to GND.

**Comment by Oitzu** [comment]
Unrelated to this problem.
Maybe follow #106.
