### ISSUE TITLE
Add button fuction but there is something wrong 

### ISSUE THREAD

**Issue by donny681** [igrr/esp32-cam-demo#58]
Eh,I want to add a fuction that the camera take photo after pressing a button.I refer to esp-idf->peripherals->gpio demo and found  that gpio_install_isr_service   is incompatible with gpio_isr_register().So sad.
Do you have a plan to add a button function.

**Comment by krzychb** [comment]
Maybe you can try [button component](https://github.com/espressif/esp-iot-solution/tree/master/components/general/button) from espressif/esp-iot-solution?

**Comment by donny681** [comment]
@krzychb Eh,it doesn't work because the demo contains gpio_install_isr_service().The demo of espressif/esp-iot-solution also registers the isr which  is incompatible with gpio_isr_register().If wanting to use button,it's better to register the isr.I'm trying to revise  the camera demo.

**Comment by igrr** [comment]
This example now also uses gpio_install_isr_service, so you should be able to add button functionality to the application.
