### ISSUE TITLE
Check that free heap is enough, why "failed to allocate frame buffer"?

### ISSUE THREAD

**Issue by jixunx** [igrr/esp32-cam-demo#72]
I am developing my project based on "esp-cam-demo".I checked the free heap before calloc. It seems the free heap size is enough, Why "failed to allocate frame buffer" .Is it because of "memory fragments"？
Is there any optimization of this problem for esp32？
Code:
`  
printf("Free heap2 :%u\n",xPortGetFreeHeapSize());
ESP_LOGD(TAG, "Allocating frame buffer (%d bytes)", s_state->fb_size);
 s_state->fb = (uint8_t*) calloc(s_state->fb_size, 1);
if (s_state->fb == NULL) {
        ESP_LOGE(TAG, "Failed to allocate frame buffer");
        err = ESP_ERR_NO_MEM;
        goto fail;
}

`

Log:

> Free heap2: 233476
I (1262) camera: Allocating frame buffer (115200 bytes)
E (1268) camera: Failed to allocate frame buffer
E (1273) main: Camera init failed with error 0x101

Best regards!

**Comment by AnyReader** [comment]
@jixunx Hi, jixunx, i meet this issus too, can you tell me how to solve it?
